### ISSUE TITLE
CI unit tests

### ISSUE THREAD

**Issue by darnfish** [AndrewBastin/GComplete#1]
Hey, just gonna drop by and say this repo is awesome!

@plusreed has written unit tests for @pent0's @Vita3K and internally for @dmfj's @songmashapp. He would be a huge help I think !!!

Keep working, Andrew!

**Comment by AndrewBastin** [comment]
Hehe, thanks for the remarks.

This wasn't a serious project, just hosted this in GitHub so I can refer here for the snippets.

I haven't touched this repo in ages :sweat_smile:

**Comment by darnfish** [comment]
Sounds good, let me know if you want to continue this in the future! Closing this out for now
